# Generated by Django 2.1.1 on 2018-09-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Data Science', 'Data Science'), ('Web Technology', 'Web Technology')], max_length=200),
        ),
    ]
