# Generated by Django 2.1.1 on 2018-09-15 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180915_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 2, 23, 43, 973270, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Data Science', 'Data Science'), ('Web Technology', 'Web Technology')], max_length=1),
        ),
    ]
